### ISSUE TITLE
[8] As a player, I want three scoreboards that separate the top ranked players of all three game modes: AVL, LList Standard, and LList Survival.

### ISSUE THREAD

**Issue by DavidTimonera** [Plongesam/data-structures-game#10]

**Comment by Jshuster17** [comment]
Added 2 more columns to the ranking table. Now the ranking table will display the user, their top AVL score, top linked list standard score and their top linked list survival score. Test is located at https://github.com/Plongesam/data-structures-game/blob/master/src/Tests/test_homepage.py.
