### ISSUE TITLE
[5] Add in API handling for keeping track of LList standard and LList survival top scores

### ISSUE THREAD

**Issue by DavidTimonera** [Plongesam/data-structures-game#80]

**Comment by Jshuster17** [comment]
There are two tests that show how the Homepage can show the top scores in the rankings table. They are located at https://github.com/Plongesam/data-structures-game/blob/llist_develop/home_page/api/tests_api.py and https://github.com/Plongesam/data-structures-game/blob/llist_develop/home_page/database/test_db.py. 
These test the API and database for the homepage which includes the top llist standard and llist survival scores.
